name: Deploy to Tencent COS

on:
  push:
    branches: [ main ] # 触发分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Astro project
      run: npm run build

    - name: Configure COS CLI
      uses: tencentyun/cos-action/configure@v2
      with:
        secret-id: ${{ secrets.COS_SECRET_ID }}
        secret-key: ${{ secrets.COS_SECRET_KEY }}
        region: ${{ secrets.COS_REGION }}
        bucket: ${{ secrets.COS_BUCKET_NAME }}

    - name: Upload to COS
      uses: tencentyun/cos-action/upload@v2
      with:
        local_path: './dist'
        remote_path: '/' # 上传到存储桶根目录
        clean: true # 上传前清空目标目录
        ignore: '.DS_Store' # 忽略文件
