name: Deploy to Tencent COS

on:
  push:
    branches: [ main ] # 触发分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Astro project
      run: npm run build

    - name: Install coscmd
      run: |
        sudo pip install coscmd
        coscmd --version
    
    - name: Configure coscmd
      run: |
        coscmd config -a ${{ secrets.COS_SECRET_ID }} \
                     -s ${{ secrets.COS_SECRET_KEY }} \
                     -b ${{ secrets.COS_BUCKET_NAME }} \
                     -r ${{ secrets.COS_REGION }}
    
    - name: Upload to COS
      run: |
        coscmd upload -r ./dist/ /
        
        # 验证上传
        echo "上传文件列表:"
        coscmd list / | head -n 10
        echo "..."
