name: Deploy to Tencent COS

on:
  push:
    branches: [ main ] # 触发分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Astro project
      run: npm run build

    # 使用 AWS CLI 上传（推荐方案）
    - name: Upload to COS via S3 API
      run: |
        pip install awscli
        aws configure set aws_access_key_id ${{ secrets.COS_SECRET_ID }}
        aws configure set aws_secret_access_key ${{ secrets.COS_SECRET_KEY }}
        aws configure set default.region ${{ secrets.COS_REGION }}
        
        aws s3 sync ./dist s3://${{ secrets.COS_BUCKET_NAME }} \
          --endpoint-url https://cos.${{ secrets.COS_REGION }}.myqcloud.com \
          --delete \
          --acl public-read
        
        echo "上传完成!"
